FROM python:3.11-slim
WORKDIR /app
COPY requirements/base.txt requirements.txt
RUN apt-get update && apt-get install -y \ 
    tesseract-ocr \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt 
COPY . .
CMD ["python", "run.py"]